cities = [
        "Paris",
        "London",
        "New York",
        "Tokyo",
        "Barcelona",
        "Dubai",
        "Berlin",
        "Amsterdam",
        "Venice",
        "Prague",
        "Bangkok",
        "Istanbul",
        "Hong Kong",
        "Rio de Janeiro",
        "Moscow",
        "Toronto",
        "San Francisco",
        "Sydney",
        "Cape Town",
        "Vienna",
        "Athens",
        "Lisbon",
        "Madrid",
        "Seoul",
        "Beijing",
        "Shanghai",
        "Singapore",
        "Bali",
        "Phuket",
        "Ho Chi Minh City",
        "Tel Aviv",
        "Cairo",
        "Casablanca",
        "Reykjavik",
        "Helsinki",
        "Copenhagen",
        "Zurich",
        "Geneva",
        "Munich",
        "Florence",
        "Milan",
        "Naples",
        "Edinburgh",
        "Glasgow",
        "Dublin",
        "Belfast",
        "Brussels",
        "Budapest",
        "Warsaw",
        "Krakow",
        "Santorini",
        "Mykonos",
        "Split",
        "Zagreb",
        "Sofia",
        "Bucharest",
        "Belgrade",
        "Ljubljana",
        "Tallinn",
        "Vilnius",
        "Baku",
        "Tbilisi",
        "Yerevan",
        "Abu Dhabi",
        "Manama",
        "Muscat",
        "Kathmandu",
        "Colombo",
        "Male",
        "Malé",
        "Victoria",
        "Port Louis",
        "Praia",
        "Zanzibar City",
        "Nairobi",
        "Addis Ababa",
        "Cusco",
        "Lima",
        "Santiago",
        "Buenos Aires",
        "Montevideo",
        "Quito",
        "Bogota",
        "Cartagena",
        "Panama City",
        "San Jose",
        "Havana",
        "Kingston",
        "Nassau",
        "Anchorage",
        "Quebec City",
        "Banff",
        "Auckland",
        "Christchurch",
        "Queenstown",
        "Suva",
        "Tahiti",
        "Bora Bora",
        "Honolulu",
        "Maui",
        "Las Vegas",
        "Chicago",
        "Boston",
        "Washington D.C.",
        "Miami",
        "New Orleans"
    ]
print(len(cities))