# Generated by Django 5.1.6 on 2025-03-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.difficulty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.difficulty'),
            preserve_default=False,
        ),
    ]
